config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # get 'line_item/index'
  # get 'line_item/show'
  # get 'line_item/new'
  # get 'line_item/create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'sessions#welcome'
  # OmniAuth
  
  post '/auth/:github/callback' => 'sessions#success'
  get '/auth/:github/callback' => 'sessions#success'
  # devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # devise_for :users, path: "auth", :controllers => {sessions: 'sessions', registrations: 'registrations', confirmations: 'confirmations', passwords: 'passwords', omniauth_callbacks: 'users/omniauth_callbacks'}

  # session routes
  get '/login', to: 'sessions#login'
  post '/success', to: 'sessions#success'
  
  get '/signup', to: 'sessions#signup'
  post '/create', to: 'sessions#create'

  delete '/logout', to: 'sessions#logout'
  get '/checkout', to: 'sessions#checkout'
  post '/checkout', to: 'sessions#checkout'

  # scope method routes
  get '/games/fps', to: 'games#fps'
  get '/games/strategy', to: 'games#strategy'
  get '/games/simulation', to: 'games#simulation'
  get '/games/platformer', to: 'games#platformer'

  
  resources :users, only: [:show, :edit, :update] do
    # nested routes
    resources :carts, only: [:show]
  end
  resources :line_items, only: [:create, :destroy]
  resources :games, only: [:index, :show]
  resources :carts, only: [:create] do
    # nested routes
    resources :line_items, only: [:new, :create]
  end  


  
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    
    has_many :line_items
    has_many :games, through: :line_items
    belongs_to :user

    def cart_total
        self.line_items.sum do |item|
            item.subtotal
        end
    end
end

app/models/game.rb
class Game < ApplicationRecord
    has_many :line_items
    has_many :carts, through: :line_items
    scope :fps, -> { where(genre: "fps") }
    scope :strategy, -> { where(genre: "strategy") }
    scope :simulation, -> { where(genre: "simulation") }
    scope :platformer, -> { where(genre: "platformer") }

    
end

app/models/line_item.rb
class LineItem < ApplicationRecord
    belongs_to :cart
    belongs_to :game
    # belongs_to :user, through: :carts
    validates :quantity, presence: true
    
    def subtotal
        self.game.price * quantity
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :carts
    has_many :line_items, through: :carts
    validates :username, :password, :email,  presence: true
    validates :username, :email,  uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?, :current_cart, :require_login
    add_flash_types :error
    before_action :current_cart

    private
  
    def current_cart
      if !session[:cart_id].nil?
        Cart.find(session[:cart_id])
      else
          @cart = Cart.new(user_id: session[:user_id])          
          @cart.save
          session[:cart_id] = @cart.id
      end
    end
  
    def current_user
      @user = User.find_by(id: session[:user_id])
    end
  
    def logged_in?
      !!current_user
      !!current_cart
    end

    def require_login      
      redirect_to root_path unless logged_in?
      flash[:errors] = "Please Sign up or Login first"
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def show
        if logged_in?            
            redirect_to user_cart_path(current_user, current_cart) unless current_cart.id == params[:id].to_i && current_user.id == params[:user_id].to_i            
        else
            require_login
        end  
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController


    def show
        @line_item = LineItem.new
        @game = Game.find_by(id: params[:id])
        redirect_to games_path unless @game
    end

    def fps

        @games = Game.fps
        render :index
    end

    def strategy
        @games = Game.strategy
        render :index
    end
    
    def simulation
        @games = Game.simulation
        render :index
    end

    def platformer
        @games = Game.platformer
        render :index
    end

    def index
    
        @games = Game.all
    end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  
  
  def index
    @line_items = LineItem.all
  end

  def show
    
  end

  def new
    @line_item = LineItem.new
  end

  def create
    @line_item = current_cart.line_items.new(line_item_params)

    if @line_item.save
      redirect_to user_cart_path(current_cart.id, current_user.id)      
    else      
      redirect_to games_path
    end
  end

  def destroy
    @cart = current_cart
    @line_item = @cart.line_items.find(params[:id])
    @line_item.destroy
    redirect_to user_cart_path(current_cart.id, current_user.id)
  end

  private

  def line_item_params
    params.require(:line_item).permit(:cart_id, :game_id, :quantity)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def signup
    new_user
  end

  def create
    @user = User.new(user_params)
    if @user.save      
      set_user(@user)
      redirect_to user_path(@user)
    else      
      render :signup
    end
  end

  def login
    new_user
  end  

  def success
    if request.env["omniauth.auth"]  
      @user = User.find_by(uid: request.env["omniauth.auth"]["uid"])
      if @user.nil?
        @user = User.create(username: request.env["omniauth.auth"]["info"]["nickname"], uid: request.env["omniauth.auth"]["uid"], password: "github")
      end
      set_user(@user)
      redirect_to user_path(@user)
    else
      @user = User.find_by(username: params[:user][:username])        
      if !@user        
        @error = "Account not found. Please try again."
        new_user
        redirect_to login_path
      elsif !@user.authenticate(params[:user][:password])          
        @error = "Password incorrect. Please try again."
        new_user
        redirect_to login_path
      else          
        set_user(@user)
        redirect_to user_path(current_user.id)
      end
    end
  end
  
  def logout
    session.clear
    redirect_to root_path
  end

  def checkout
    @cart = current_cart
    session.delete(:cart_id)
  end
  
  
  private

  def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def new_user
    @user = User.new
  end

  def set_user(user)
    session[:user_id] = user.id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    

    def show
        if logged_in?
            redirect_to user_path(current_user) unless current_user.id == params[:id].to_i
            # flash[:errors] = "You can only view your own profile"
        else
            require_login
        end        
    end

    def edit
        current_user
    end

    def update
        current_user.update(update_params)
        redirect_to user_path(current_user)
    end

    private

    def update_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/line_item_helper.rb
module LineItemHelper
end

app/views/carts/show.html.erb
<h1><%= current_cart.user.username %>'s' Cart:</h1>

<% current_cart.line_items.each do |line_item| %>
<p><strong>Game:</strong> <%= line_item.game.name %></p>
<p><strong>Quantity:</strong> <%= line_item.quantity %></p>
<p><strong>Price:</strong> $<%= line_item.game.price %></p>
<p><strong>Subtotal:</strong> $<%= line_item.subtotal %></p>
<%= button_to "Remove From Cart", line_item_path(line_item), method: :delete %>
<br>
<% end %>

<h3><strong>Total:</strong> $<%= current_cart.cart_total %></h3>
<br>
<%= button_to "Checkout", checkout_path %>
<br>
<%= link_to 'Continue Shopping', games_path %>
<br>
<br>

app/views/games/index.html.erb

<h1>Games View</h1>

<%= link_to 'All Games', games_path%>
<%= link_to 'FPS', games_fps_path%>
<%= link_to 'Strategy', games_strategy_path %>
<%= link_to 'Simulation', games_simulation_path %>
<%= link_to 'Platformer', games_platformer_path %>

<ul>
<% @games.each do |game| %>
<li><%= link_to game.name, game_path(game) %></li>
<% end %>
</ul>

app/views/games/show.html.erb




<h1><%= @game.name %></h1>
<ul>
    <li>Desc: <%= @game.description %></li>
    <li>Genre: <%= @game.genre %></li>
    <li>Price: $<%= @game.price %></li>
</ul>
<% if logged_in? %>
    <%= form_for @line_item  do |f|%>
        <%= f.hidden_field :game_id, value: @game.id %>
        <%= f.number_field :quantity, value: 1, :min =>  1%>
        <%= f.submit "Add to Cart "%>
    <% end %>
<% end %>
<%= link_to 'Back to Games', games_path %>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameStoop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="/app/assets/stylesheets/styles.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Syne+Mono&display=swap" rel="stylesheet">
  </head>

  <body>

  <div >
    <nav class="border" > 
      <% if !logged_in? %>    
        <%= link_to 'Home', root_path %> 
        <% end %>
      <% if !!session[:cart_id] %>
        <%= link_to 'Home', user_path(session[:user_id]) %> 
        <%= link_to "Your Cart: #{current_cart.line_items.size} items with a value of #{current_cart.cart_total }$", user_cart_path(current_cart.id, session[:user_id]) %>
      <% end %>
      <%= link_to 'View Games', games_path %> 
    </nav>
  </div>

  
  <div class="border">  
        
    <%= yield %>
    
    <% if logged_in? %>
    <%= link_to 'Log Out', logout_path, method:'delete' %>
    <% end %>  
  </div>
  

  
  </body>
</html>

app/views/users/_game_library.html.erb
<ul>
    <% current_user.carts.each do |cart| %>
        <% cart.line_items.each do |line_item| %>
            <li><%=line_item.game.name%></li>
        <%end%>
    <%end%>
</ul>

app/views/users/edit.html.erb
<h1>Changing <%=current_user.username %>'s Profile</h1>

<%= form_for(current_user) do |f| %>
    <%= f.label :email %>
    <br>
    <%= f.text_field :email%>
    <br>
    <%= f.label :password %>
    <br>
    <%= f.password_field :password%>
    <br>
    <%= f.label :password_confirmation %>
    <br>
    <%= f.password_field :password_confirmation %>
    <br>
    <%= f.submit %>
<% end %>

app/views/users/show.html.erb


<h1>Player <%=current_user.username%>'s Home Page</h1>
<p>Email: <%= current_user.email%></p>
<%= link_to 'Edit Your Profile', edit_user_path(current_user) %>
<br>

<h3>Your Game Library</h3>
<%= render partial: '/users/game_library' %>